config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :imovel
  
  resources :anuncio
    
  root 'welcome#index'
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord
   has_attached_file :image,
                  url: "/system/:hash.:extension",
                  hash_secret: "abc123"
    validates_attachment :image, presence: true,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
                     size: { in: 0..500.kilobytes }
   
   belongs_to :imovel
   
   validates_presence_of :imovel_id
   validates_associated :imovel
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imovel.rb
class Imovel < ApplicationRecord
    has_many :anuncios, dependent: :destroy
    
end

app/controllers/anuncio_controller.rb
class AnuncioController < ApplicationController
    
     def index
        @anuncio = Anuncio.all
     end
    
    def show
        @anuncio = Anuncio.find(params[:id])
    end
    
    def new
      @anuncio = Anuncio.new
    end
    
    def edit
      @anuncio = Anuncio.find(params[:id])
    end
    
    def create
       @anuncio = Anuncio.new(anuncio_params)
       if @anuncio.save
          redirect_to @anuncio
       else
          render 'new'
       end
    end
    
    def update
       @anuncio = Anuncio.find(params[:id])
       if @anuncio.update_attributes(anuncio_params)
         flash[:success] = "Anúncio atualizado"
         redirect_to @anuncio
       else
          render 'edit'
       end
    end
    
    def destroy
      
       Anuncio.find(params[:id]).destroy
      flash[:success] = "Anúncio deletado"
      redirect_to anuncio_index_path
    
    end
    
    
    private
    
        def anuncio_params
            params.require(:anuncio).permit(:titulo, :descricao, :depoimentoDONO, :imovel_id, :image)
        end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/imovel_controller.rb
class ImovelController < ApplicationController
   
    def index
        @imovel = Imovel.all
    end
    
    def show
        @imovel = Imovel.find(params[:id])
    end
    
    def new
      @imovel = Imovel.new
    end
    
    def edit
      @imovel = Imovel.find(params[:id])
    end
    
    def create
       @imovel = Imovel.new(imovel_params)
       if @imovel.save
          redirect_to @imovel
       else
          render 'new'
       end
    end
    
    def update
       @imovel = Imovel.find(params[:id])
       if @imovel.update_attributes(imovel_params)
         flash[:success] = "Imovel atualizado"
         redirect_to @imovel
       else
          render 'edit'
       end
    end
    
    def destroy
     
      Imovel.find(params[:id]).destroy
      flash[:success] = "Imóvel deletado"
      redirect_to imovel_index_path
    
    end
    
    
    private
    
        def imovel_params
            params.require(:imovel).permit(:codigo, :tipo, :valor, :valorIPTU, :valorCondominio, :numQUARTOS, :numSUITES, :numBANHEIROS, :numVAGAS, :areaTOTAL, :extras)
        end
    
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/anuncio_helper.rb
module AnuncioHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imovel_helper.rb
module ImovelHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/anuncio/edit.html.erb
<% provide(:title, "Editar Anúncios") %>
<div class="container">

    <div class="row">
<h1>Editar Anúncios</h1>

<div class="content">

    <%= form_for(@anuncio) do |f| %>
      
  <p>
    <%= f.label :titulo %>
    <%= f.text_field :titulo, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.label :descricao %>
    <%= f.text_area :descricao, :class => "form-control" %>
  </p>
  
  <p>
    <%= f.label :depoimentoDONO %>
    <%= f.text_area :depoimentoDONO, :class => "form-control" %>
  </p>
  
  <p>
    <%= f.label :imovel_id %>
    <%= f.text_field :imovel_id, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.file_field :image, :class => "form-control margin-t-10" %>
  </p>
 
  <p>
    <%= f.submit "Salvar", :class => "btn btn-primary btn-lg margin-t-10" %>
    
    <a href="/anuncio" class="btn btn-primary btn-lg margin-t-10">Voltar</a></a>
  </p>
<% end %>

</div>
</div>
</div>

app/views/anuncio/index.html.erb
 <div class="container">
   <h1>Listando Anúncios</h1>
   <div class="col-xs-12">
     <div class="table-responsive">
<table class="table table-hover">
  <tr>
    <th>Título</th>
    <th>Descrição</th>
    <th>Depoimento Dono</th>
    <th>Identificação do imóvel</th>
    <th>Imagem</th>
  </tr>
 
  <% @anuncio.each do |anuncio| %>
    <tr>
      <td><%= anuncio.titulo %></td>
      <td><%= anuncio.descricao %></td>
      <td><%= anuncio.depoimentoDONO %></td>
      <td><%= anuncio.imovel_id %></td></td>
      <td><%= image_tag anuncio.image, :class => "img-circle" %></td>
      <td><%= link_to 'Show', anuncio_path(anuncio) %></td>
      <td><%= link_to 'Editar', edit_anuncio_path(anuncio) %></td>
      <td><%= link_to "delete", anuncio, method: :delete,
                                  data: { confirm: "Certeza?" } %></td>
    </tr>
  <% end %>
</table>

</div>

<%= link_to "Home", root_path, :class => "btn btn-primary btn-lg" %>
</div>
</div>

app/views/anuncio/new.html.erb
<div class="container">
    <div class="row">
    <h1>Cadastrar Anúncios</h1>
    <div class="content">

<%= form_for :anuncio, url: anuncio_index_path, html: { multipart: true } do |f| %>

  <p>
    <%= f.label :titulo %>
    <%= f.text_field :titulo, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.label :descricao %>
    <%= f.text_area :descricao, :class => "form-control" %>
  </p>
  
  <p>
    <%= f.label :depoimentoDONO %>
    <%= f.text_area :depoimentoDONO, :class => "form-control" %>
  </p>
  
  <p>
    <%= f.label :imovel_id %>
    <%= f.text_field :imovel_id, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :image %>
    <%= f.file_field :image, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.submit "Cadastrar", :class => "btn btn-primary btn-lg margin-t-10" %>
    <a href="/anuncio" class="btn btn-primary btn-lg margin-t-10">Voltar</a>
  </p>
<% end %>

</div>
</div>
</div>

app/views/anuncio/show.html.erb
<div class="container">

    <div class="row">

        <h1>Registro de Anúncio</h1>

        <div class="content">

            <p>
                <strong>Título:</strong>
                <%= @anuncio.titulo %>
            </p>

            <p>
                <strong>Descrição:</strong>
                <%= @anuncio.descricao %>
            </p>


            <p>
                <strong>Depoimento do Dono:</strong>
                <%= @anuncio.depoimentoDONO %>
            </p>

            <p>
                <strong>Identificação do Imóvel:</strong>
                <%= @anuncio.imovel_id %>
            </p>

            <p>
                <%= image_tag @anuncio.image %>
            </p>
            
            <a class="btn btn-primary btn-lg" href="/anuncio">Voltar</a>
            
        </div>
    </div>
</div>

app/views/imovel/edit.html.erb
<% provide(:title, "Editar Imoveis") %>

<div class="container">

    <div class="row">
     
<h1>Editar Imoveis</h1>

<div class="content">
    <%= form_for(@imovel) do |f| %>
      
  <p>
    <%= f.label :codigo %>
    <%= f.text_field :codigo, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.label :tipo %>
    <%= f.text_field :tipo, :class => "form-control"%>
  </p>
  
  <p>
    <%= f.label :valor %>
    <%= f.text_field :valor, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :valorIPTU %>
    <%= f.text_field :valorIPTU, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :valorCondominio %>
    <%= f.text_field :valorCondominio, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numQUARTOS %>
    <%= f.text_field :numQUARTOS, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numSUITES%>
    <%= f.text_field :numSUITES, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numBANHEIROS%>
    <%= f.text_field :numBANHEIROS, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numVAGAS%>
    <%= f.text_field :numVAGAS, :class => "form-control" %>
   </p>
  
  <p>
    <%= f.label :areaTOTAL%>
    <%= f.text_field :areaTOTAL, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :extras%>
    <%= f.text_area :extras, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.submit "Salvar", :class => "btn btn-primary btn-lg margin-t-10" %>
    <a href="/imovel" class="btn btn-primary btn-lg margin-t-10">voltar</a>
  </p>
<% end %>

</div>
</div>
</div>

app/views/imovel/index.html.erb
<div class="container">
    <h1>Listando Imoveis</h1>
    <div class="col-xs-12">
        <div class="table-responsive">
            <table class="table table-hover">
                <tr>
                    <th>Código</th>
                    <th>Tipo</th>
                    <th>Valor</th>
                    <th>Valor IPTU</th>
                    <th>Valor Condominio</th>
                    <th>Número de Quartos</th>
                    <th>Número de Suites</th>
                    <th>Número de Banheiros</th>
                    <th>Número de Vagas</th>
                    <th>Área Total</th>
                    <th>Extras</th>
                </tr>

                <% @imovel.each do |imovel| %>
                    <tr>
                        <td>
                            <%= imovel.codigo %>
                        </td>
                        <td>
                            <%= imovel.tipo %>
                        </td>
                        <td>
                            <%= imovel.valor %>
                        </td>
                        <td>
                            <%= imovel.valorIPTU %>
                        </td>
                        <td>
                            <%= imovel.valorCondominio %>
                        </td>
                        <td>
                            <%= imovel.numQUARTOS %>
                        </td>
                        <td>
                            <%= imovel.numSUITES %>
                        </td>
                        <td>
                            <%= imovel.numBANHEIROS %>
                        </td>
                        <td>
                            <%= imovel.numVAGAS %>
                        </td>
                        <td>
                            <%= imovel.areaTOTAL %>
                        </td>
                        <td>
                            <%= imovel.extras %>
                        </td>
                        <td>
                            <%= link_to 'Show', imovel_path(imovel) %>
                        </td>
                        <td>
                            <%= link_to 'Editar', edit_imovel_path(imovel) %>
                        </td>
                        <td>
                            <%= link_to "delete", imovel, method: :delete, data: { confirm: "Deseja realmente deletar o registro?" } %>
                        </td>
                    </tr>
                    <% end %>
            </table>

        </div>
        <%= link_to "Home", root_path, :class => "btn btn-primary btn-lg" %>
    </div>
</div>

app/views/imovel/new.html.erb
<div class="container">
     <div class="row">
    <h1>Cadastrar Imóvel</h1>
    
    <div class="content">

<%= form_for :imovel, url: imovel_index_path do |f| %>

  <p>
    <%= f.label :codigo %>
    <%= f.text_field :codigo, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.label :tipo %>
    <%= f.text_field :tipo, :class => "form-control" %>
  </p>
  
  <p>
    <%= f.label :valor %>
    <%= f.text_field :valor, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :valorIPTU %>
    <%= f.text_field :valorIPTU, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :valorCondominio %>
    <%= f.text_field :valorCondominio, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numQUARTOS %>
    <%= f.text_field :numQUARTOS, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numSUITES%>
    <%= f.text_field :numSUITES, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numBANHEIROS%>
    <%= f.text_field :numBANHEIROS, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :numVAGAS%>
    <%= f.text_field :numVAGAS, :class => "form-control" %>
  </p>
  
  <p>
    <%= f.label :areaTOTAL%>
    <%= f.text_field :areaTOTAL, :class => "form-control" %>
  </p>
   
   <p>
    <%= f.label :extras%>
    <%= f.text_area :extras, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.submit "Cadastrar", :class => "btn btn-primary btn-lg margin-t-10" %>
    <a href="/imovel" class="btn btn-primary btn-lg margin-t-10">Voltar</a>
  </p>
<% end %>

</div>
</div>
</div>

app/views/imovel/show.html.erb
<div class="container">
    <div class="row">
        <h1>Registro de imóvel</h1>
        
        <div class="content">
            <p>
                <strong>Código:</strong>
                <%= @imovel.codigo %>
            </p>

            <p>
                <strong>Tipo:</strong>
                <%= @imovel.tipo %>
            </p>


            <p>
                <strong>Valor:</strong>
                <%= @imovel.valor %>
            </p>

            <p>
                <strong>Valor IPTU:</strong>
                <%= @imovel.valorIPTU %>
            </p>
            <p>
                <strong>Valor Condomínio:</strong>
                <%= @imovel.valorCondominio %>
            </p>
            <p>
                <strong>Número de Quartos:</strong>
                <%= @imovel.numQUARTOS %>
            </p>
            <p>
                <strong>Número de Suites:</strong>
                <%= @imovel.numSUITES %>
            </p>
            <p>
                <strong>Número de banheiros:</strong>
                <%= @imovel.numBANHEIROS %>
            </p>
            <p>
                <strong>Número de vagas:</strong>
                <%= @imovel.numVAGAS %>
            </p>
            <p>
                <strong>Área Total:</strong>
                <%= @imovel.areaTOTAL %>
            </p>
            <p>
                <strong>Extras:</strong>
                <%= @imovel.extras %>
            </p>

            <a class="btn btn-primary btn-lg margin-t-10" href="/imovel">Voltar</a>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imobiliaria on Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">


    
    <div class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
            <li><a href="/imovel">Mostrar Imóveis</a></li>
            <li><a href="/imovel/new">Cadastrar Imóveis</a></li>
            <li><a href="/anuncio">Mostrar Anúncios</a></li>
            <li><a href="/anuncio/new">Cadastrar Anúncios</a></li>
        </ul>
    </div>
    
    <div class="row">
        <h1>Bem Vindo!</h1>
    </div>
    
</div>